services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - PORT=5000
      - ENV=DEV
      - AUDITLY_HOST=http://127.0.0.1:8080
      - DB_HOST=127.0.0.1
      - DB_PORT=5432
      - DB_USER=root
      - DB_PWD=root
      - DB_NAME=sdb
    ports:
      - 5000:5000

  db:
    image: postgres:17-alpine
    volumes: 
      - ./sql:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=sdb
    ports:
      - 5432:5432
