CREATE TABLE SCHEDULED_TASKS (
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    NAME TEXT NOT NULL,
    PAYLOAD JSONB NOT NULL,
    RUN_AT TIMESTAMPTZ NOT NULL,
    STATUS TEXT NOT NULL DEFAULT 'pending', -- pending | running | completed | failed | canceled
    ATTEMPTS INTEGER NOT NULL DEFAULT 0,
    MAX_ATTEMPTS INTEGER NOT NULL DEFAULT 3,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT now(),
    UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT now()
);

